<a href="https://colab.research.google.com/github/saimino/LikeLion_DataCourse/blob/main/%EC%B6%94%EC%B2%9C%EC%8B%9C%EC%8A%A4%ED%85%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#21 - 10 - 29 mino
import numpy as np

#유저기반 추천시스템
#(싫다 : 0, 모르겠다:1, 좋다:2) 로 설정해서 추천시스템 만들어보기
user1 = np.array([2,2,1,2])
user2 = np.array([1,1,2,1])
user3 = np.array([2,2,1,0])

rMatrix = np.vstack (( user1, user2, user3))
print(rMatrix.shape)
rMatrix

(3, 4)


array([[2, 2, 1, 2],
       [1, 1, 2, 1],
       [2, 2, 1, 0]])

In [6]:
from sklearn.metrics.pairwise import cosine_similarity

cosineSim = cosine_similarity(rMatrix)

print(cosineSim.shape)
cosineSim # 코사인 유사도 메트릭스 (유저기반)
# (유저3이 가장 유사한 유저는 유저1이다. -> 유저1이 좋아하는 것을 유저3에게 추천)

(3, 3)


array([[1.        , 0.83862787, 0.83205029],
       [0.83862787, 1.        , 0.75592895],
       [0.83205029, 0.75592895, 1.        ]])

In [8]:
#아이템 기반 추천시스템
rMatrix_t = np.transpose(rMatrix)
rMatrix_t

array([[2, 1, 2],
       [2, 1, 2],
       [1, 2, 1],
       [2, 1, 0]])

In [9]:
cosineSim_t = cosine_similarity(rMatrix_t) #피자 치킨 김밥 탕수육 순이라고 한다면,
cosineSim_t

array([[1.        , 1.        , 0.81649658, 0.74535599],
       [1.        , 1.        , 0.81649658, 0.74535599],
       [0.81649658, 0.81649658, 1.        , 0.73029674],
       [0.74535599, 0.74535599, 0.73029674, 1.        ]])

In [10]:
# 아이템기반 협업 필터링을 이용한  영화 추천 시스템
import pandas as pd
import numpy as np
import sklearn
from sklearn.decomposition import TruncatedSVD
from IPython.display import display, Image

In [29]:
# 장르 분야
columns = ['item_id', 'movie title', 'release date', 'video release date', 'IMDb URL', 
           'unknown', 'Action', 'Adventure', 'Animation', 'Childrens', 
           'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 
           'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 
           'Sci-Fi', 'Thriller', 'War', 'Western']

movies = pd.read_csv('ml10k/u.item', sep='|', names=columns, encoding='latin-1')

movie_names = movies[['item_id', 'movie title']]
c_movies_data = pd.merge(df, movie_names, on='item_id')
print(c_movies_data.shape)
c_movies_data.head()

(100000, 5)


user_id  item_id  rating  timestamp   movie title
0      196      242       3  881250949  Kolya (1996)
1       63      242       3  875747190  Kolya (1996)
2      226      242       5  883888671  Kolya (1996)
3      154      242       3  879138235  Kolya (1996)
4      306      242       5  876503793  Kolya (1996)

In [30]:
movies

item_id                                movie title  ... War  Western
0           1                           Toy Story (1995)  ...   0        0
1           2                           GoldenEye (1995)  ...   0        0
2           3                          Four Rooms (1995)  ...   0        0
3           4                          Get Shorty (1995)  ...   0        0
4           5                             Copycat (1995)  ...   0        0
...       ...                                        ...  ...  ..      ...
1677     1678                          Mat' i syn (1997)  ...   0        0
1678     1679                           B. Monkey (1998)  ...   0        0
1679     1680                       Sliding Doors (1998)  ...   0        0
1680     1681                        You So Crazy (1994)  ...   0        0
1681     1682  Scream of Stone (Schrei aus Stein) (1991)  ...   0        0

[1682 rows x 24 columns]

In [26]:
rating_crosstab = c_movies_data.pivot_table(values='rating', 
                                            index='user_id', 
                                            columns='movie title', fill_value=0)
rating_crosstab.head()

movie title  'Til There Was You (1997)  ...  Á köldum klaka (Cold Fever) (1994)
user_id                                 ...                                    
1                                    0  ...                                   0
2                                    0  ...                                   0
3                                    0  ...                                   0
4                                    0  ...                                   0
5                                    0  ...                                   0

[5 rows x 1664 columns]

In [27]:
X = rating_crosstab.T
print(X.shape)

(1664, 943)


In [28]:
SVD = TruncatedSVD(n_components=12, random_state=5) # SVD로 차원축소
resultant_matrix = SVD.fit_transform(X)
resultant_matrix.shape

(1664, 12)

In [31]:
### correlation matrix 아이템 기반
corr_mat = np.corrcoef(resultant_matrix)
print( corr_mat.shape )
corr_mat

(1664, 1664)


array([[ 1.        , -0.11677136,  0.50912612, ...,  0.38185536,
         0.1925393 ,  0.49767897],
       [-0.11677136,  1.        ,  0.05531997, ...,  0.16334854,
         0.52127277,  0.28134103],
       [ 0.50912612,  0.05531997,  1.        , ...,  0.76371825,
         0.43466401,  0.19050485],
       ...,
       [ 0.38185536,  0.16334854,  0.76371825, ...,  1.        ,
         0.18096315,  0.12145833],
       [ 0.1925393 ,  0.52127277,  0.43466401, ...,  0.18096315,
         1.        ,  0.20183785],
       [ 0.49767897,  0.28134103,  0.19050485, ...,  0.12145833,
         0.20183785,  1.        ]])

In [34]:
rating_crosstab.columns.get_loc("101 Dalmatians (1996)")

2

In [35]:
col_idx = rating_crosstab.columns.get_loc("101 Dalmatians (1996)")
corr_specific = corr_mat[col_idx]    # Star Wars (1977)의 위치 행 획득
print(corr_specific.shape) 

(1664,)


In [36]:
result = pd.DataFrame({'corr_specific':corr_specific, 'Movies': rating_crosstab.columns})
print(result.shape)
result.head()

(1664, 2)


corr_specific                     Movies
0       0.509126  'Til There Was You (1997)
1       0.055320               1-900 (1994)
2       1.000000      101 Dalmatians (1996)
3       0.373695        12 Angry Men (1957)
4       0.275763                 187 (1997)

In [37]:
result.sort_values('corr_specific', ascending=False).head(10)

corr_specific                                           Movies
2         1.000000                            101 Dalmatians (1996)
693       0.944401  Homeward Bound II: Lost in San Francisco (1996)
713       0.931816              Hunchback of Notre Dame, The (1996)
659       0.922813                           Harriet the Spy (1996)
46        0.911541                   All Dogs Go to Heaven 2 (1996)
805       0.902762                                    Kazaam (1996)
435       0.899906                               Dragonheart (1996)
23        0.898412              Adventures of Pinocchio, The (1996)
764       0.892500                                      Jack (1996)
505       0.884585               Father of the Bride Part II (1995)